# LiteLLM Proxy Configuration

model_list:
  - model_name: mock
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: ""
      mock_response: "pong"

litellm_settings:
  drop_params: true
  callbacks: litellm_custom_callbacks.proxy_handler_instance

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  store_model_in_db: true
