-- Auto-generated by scripts/generate_init_sql.py

INSERT INTO ai_manufacturers (id, code, name, category, default_base_url, doc_url, enabled, created_at, updated_at)
VALUES (13005216788516864, 'volcengine', 'Volcengine', 'image', 'https://ark.cn-beijing.volces.com/api/v3', 'https://www.volcengine.com/docs/82379/1541523', true, NOW(), NOW())
ON CONFLICT (code, category) DO UPDATE SET 
    default_base_url = EXCLUDED.default_base_url,
    doc_url = EXCLUDED.doc_url,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 13005216788516865, id, 'doubao-seedream-5.0-lite', 'Doubao Seedream 5.0 Lite', '{"max_resolution": "3K"}'::jsonb, '{"type": "object", "properties": {"size": {"type": "string", "enum": ["2K", "3K"], "default": "2K", "title": "Resolution"}, "prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "sequential_image_generation": {"type": "string", "enum": ["auto", "disabled"], "default": "disabled", "title": "Group Generation"}, "watermark": {"type": "boolean", "default": true, "title": "Watermark"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'volcengine' AND category = 'image'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 13005216788516866, id, 'doubao-seedream-4.5', 'Doubao Seedream 4.5', '{}'::jsonb, '{"type": "object", "properties": {"size": {"type": "string", "title": "Resolution (WxH)", "default": "2048x2048"}, "prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "watermark": {"type": "boolean", "default": true, "title": "Watermark"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'volcengine' AND category = 'image'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_manufacturers (id, code, name, category, default_base_url, doc_url, enabled, created_at, updated_at)
VALUES (13005216788516867, 'aliyun', 'Aliyun Wanxiang', 'image', 'https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation', 'https://help.aliyun.com/zh/model-studio/text-to-image-v2-api-reference', true, NOW(), NOW())
ON CONFLICT (code, category) DO UPDATE SET 
    default_base_url = EXCLUDED.default_base_url,
    doc_url = EXCLUDED.doc_url,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 13005216788516868, id, 'wan2.6-t2i', 'Wanxiang 2.6', '{}'::jsonb, '{"type": "object", "properties": {"size": {"type": "string", "default": "1280*1280", "title": "Size"}, "prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "n": {"type": "integer", "minimum": 1, "maximum": 4, "default": 1, "title": "Number of Images"}, "watermark": {"type": "boolean", "default": false, "title": "Watermark"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'aliyun' AND category = 'image'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 13005216788516869, id, 'wan2.5-t2i-preview', 'Wanxiang 2.5 Preview', '{}'::jsonb, '{"type": "object", "properties": {"size": {"type": "string", "default": "1280*1280", "title": "Size"}, "prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'aliyun' AND category = 'image'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_manufacturers (id, code, name, category, default_base_url, doc_url, enabled, created_at, updated_at)
VALUES (13005216788516870, 'vidu', 'Vidu', 'video', 'https://api.vidu.cn/ent/v2', 'https://platform.vidu.cn/docs/text-to-video', true, NOW(), NOW())
ON CONFLICT (code, category) DO UPDATE SET 
    default_base_url = EXCLUDED.default_base_url,
    doc_url = EXCLUDED.doc_url,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 13005216788516871, id, 'viduq3-pro', 'Vidu Q3 Pro', '{}'::jsonb, '{"type": "object", "properties": {"prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "duration": {"type": "integer", "enum": [5, 10], "default": 5, "title": "Duration (s)"}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16", "1:1"], "default": "16:9", "title": "Aspect Ratio"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'vidu' AND category = 'video'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 13005216788516872, id, 'viduq3-turbo', 'Vidu Q3 Turbo', '{}'::jsonb, '{"type": "object", "properties": {"prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "duration": {"type": "integer", "default": 5, "title": "Duration (s)"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'vidu' AND category = 'video'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_manufacturers (id, code, name, category, default_base_url, doc_url, enabled, created_at, updated_at)
VALUES (13005216788516873, 'google', 'Google Gemini', 'image', 'https://generativelanguage.googleapis.com/v1beta', 'https://ai.google.dev/gemini-api/docs/image-generation', true, NOW(), NOW())
ON CONFLICT (code, category) DO UPDATE SET 
    default_base_url = EXCLUDED.default_base_url,
    doc_url = EXCLUDED.doc_url,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 13005216788516874, id, 'gemini-3-pro-image-preview', 'Gemini 3 Pro Image', '{}'::jsonb, '{"type": "object", "properties": {"prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "aspectRatio": {"type": "string", "enum": ["16:9", "1:1", "4:3"], "default": "1:1", "title": "Aspect Ratio"}, "imageSize": {"type": "string", "enum": ["1K", "2K", "4K"], "default": "1K", "title": "Resolution"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'google' AND category = 'image'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();
