-- Auto-generated by scripts/generate_init_sql.py

INSERT INTO ai_manufacturers (id, code, name, category, default_base_url, doc_url, enabled, created_at, updated_at)
VALUES ('705db6e4-5697-5580-9e3f-6d0b162150b9', 'volcengine', 'Volcengine', 'image', 'https://ark.cn-beijing.volces.com/api/v3', 'https://www.volcengine.com/docs/82379/1541523', true, NOW(), NOW())
ON CONFLICT (code, category) DO UPDATE SET 
    default_base_url = EXCLUDED.default_base_url,
    doc_url = EXCLUDED.doc_url,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 'e305fbd5-febf-5267-82a6-4f3bf15b7f40', id, 'doubao-seedream-5.0-lite', 'Doubao Seedream 5.0 Lite', '{"max_resolution": "3K"}'::jsonb, '{"type": "object", "properties": {"size": {"type": "string", "enum": ["2K", "3K"], "default": "2K", "title": "Resolution"}, "prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "sequential_image_generation": {"type": "string", "enum": ["auto", "disabled"], "default": "disabled", "title": "Group Generation"}, "watermark": {"type": "boolean", "default": true, "title": "Watermark"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'volcengine' AND category = 'image'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 'e14ac1a5-7acd-5089-884b-36595bdfbce0', id, 'doubao-seedream-4.5', 'Doubao Seedream 4.5', '{}'::jsonb, '{"type": "object", "properties": {"size": {"type": "string", "title": "Resolution (WxH)", "default": "2048x2048"}, "prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "watermark": {"type": "boolean", "default": true, "title": "Watermark"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'volcengine' AND category = 'image'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_manufacturers (id, code, name, category, default_base_url, doc_url, enabled, created_at, updated_at)
VALUES ('621d6bc9-28ab-50ef-891e-3dee15facfba', 'aliyun', 'Aliyun Wanxiang', 'image', 'https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation', 'https://help.aliyun.com/zh/model-studio/text-to-image-v2-api-reference', true, NOW(), NOW())
ON CONFLICT (code, category) DO UPDATE SET 
    default_base_url = EXCLUDED.default_base_url,
    doc_url = EXCLUDED.doc_url,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 'dd272a23-9070-51df-a4af-af4653abdad0', id, 'wan2.6-t2i', 'Wanxiang 2.6', '{}'::jsonb, '{"type": "object", "properties": {"size": {"type": "string", "default": "1280*1280", "title": "Size"}, "prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "n": {"type": "integer", "minimum": 1, "maximum": 4, "default": 1, "title": "Number of Images"}, "watermark": {"type": "boolean", "default": false, "title": "Watermark"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'aliyun' AND category = 'image'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT '1c50defa-8a4f-558b-9aed-2aa697125658', id, 'wan2.5-t2i-preview', 'Wanxiang 2.5 Preview', '{}'::jsonb, '{"type": "object", "properties": {"size": {"type": "string", "default": "1280*1280", "title": "Size"}, "prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'aliyun' AND category = 'image'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_manufacturers (id, code, name, category, default_base_url, doc_url, enabled, created_at, updated_at)
VALUES ('e892c087-877b-55c7-b1e7-e3627fe80857', 'vidu', 'Vidu', 'video', 'https://api.vidu.cn/ent/v2', 'https://platform.vidu.cn/docs/text-to-video', true, NOW(), NOW())
ON CONFLICT (code, category) DO UPDATE SET 
    default_base_url = EXCLUDED.default_base_url,
    doc_url = EXCLUDED.doc_url,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 'fb808e5b-8258-5e80-8ca3-7ddf2c635e43', id, 'viduq3-pro', 'Vidu Q3 Pro', '{}'::jsonb, '{"type": "object", "properties": {"prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "duration": {"type": "integer", "enum": [5, 10], "default": 5, "title": "Duration (s)"}, "aspect_ratio": {"type": "string", "enum": ["16:9", "9:16", "1:1"], "default": "16:9", "title": "Aspect Ratio"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'vidu' AND category = 'video'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT 'b1ece299-6970-53f3-a117-32e27664a900', id, 'viduq3-turbo', 'Vidu Q3 Turbo', '{}'::jsonb, '{"type": "object", "properties": {"prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "duration": {"type": "integer", "default": 5, "title": "Duration (s)"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'vidu' AND category = 'video'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();


INSERT INTO ai_manufacturers (id, code, name, category, default_base_url, doc_url, enabled, created_at, updated_at)
VALUES ('f0ee06a5-0e1d-562e-a8ea-a7c31aec65dc', 'google', 'Google Gemini', 'image', 'https://generativelanguage.googleapis.com/v1beta', 'https://ai.google.dev/gemini-api/docs/image-generation', true, NOW(), NOW())
ON CONFLICT (code, category) DO UPDATE SET 
    default_base_url = EXCLUDED.default_base_url,
    doc_url = EXCLUDED.doc_url,
    updated_at = NOW();


INSERT INTO ai_models (id, manufacturer_id, code, name, model_metadata, param_schema, enabled, created_at, updated_at)
SELECT '927734a8-f7dc-58a2-a6ad-e1a7af67fddd', id, 'gemini-3-pro-image-preview', 'Gemini 3 Pro Image', '{}'::jsonb, '{"type": "object", "properties": {"prompt": {"type": "string", "title": "Prompt", "ui:widget": "textarea"}, "aspectRatio": {"type": "string", "enum": ["16:9", "1:1", "4:3"], "default": "1:1", "title": "Aspect Ratio"}, "imageSize": {"type": "string", "enum": ["1K", "2K", "4K"], "default": "1K", "title": "Resolution"}}, "required": ["prompt"]}'::jsonb, true, NOW(), NOW()
FROM ai_manufacturers WHERE code = 'google' AND category = 'image'
ON CONFLICT (manufacturer_id, code) DO UPDATE SET
    param_schema = EXCLUDED.param_schema,
    model_metadata = EXCLUDED.model_metadata,
    updated_at = NOW();
