[mypy]
python_version = 3.12
files = app/**/*.py
follow_imports = skip
ignore_missing_imports = True
strict = False
disallow_untyped_defs = False
disallow_incomplete_defs = False
disallow_untyped_calls = False
disallow_subclassing_any = False
no_implicit_reexport = False
warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
