"""add_asset_doc_node_id

Revision ID: 37821a04fec6
Revises: 83ccec4a37bd
Create Date: 2026-02-23 00:50:38.192770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '37821a04fec6'
down_revision: Union[str, None] = '83ccec4a37bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('doc_node_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assets', 'file_nodes', ['doc_node_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'doc_node_id')
    # ### end Alembic commands ###
