"""add_ai_chat_session_tasks_table

Revision ID: a028e9aa7278
Revises: a1b2c3d4e5f8
Create Date: 2026-02-27 12:51:55.342933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a028e9aa7278'
down_revision: Union[str, None] = 'a1b2c3d4e5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_session_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'task_id', name='uq_ai_chat_session_tasks_session_task')
    )
    op.create_index('idx_ai_chat_session_tasks_created_at', 'ai_chat_session_tasks', ['created_at'], unique=False)
    op.create_index('idx_ai_chat_session_tasks_session', 'ai_chat_session_tasks', ['session_id'], unique=False)
    op.create_index('idx_ai_chat_session_tasks_task', 'ai_chat_session_tasks', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_chat_session_tasks_task', table_name='ai_chat_session_tasks')
    op.drop_index('idx_ai_chat_session_tasks_session', table_name='ai_chat_session_tasks')
    op.drop_index('idx_ai_chat_session_tasks_created_at', table_name='ai_chat_session_tasks')
    op.drop_table('ai_chat_session_tasks')
    # ### end Alembic commands ###
