"""add_asset_source

Revision ID: fdad15920802
Revises: 8c9d0e1f2a3b
Create Date: 2026-02-22 01:06:42.381713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdad15920802'
down_revision: Union[str, None] = '8c9d0e1f2a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_llm_usage_daily_user_date', table_name='llm_usage_daily')
    op.drop_table('llm_usage_daily')
    op.drop_index('idx_llm_custom_services_created_at', table_name='llm_custom_services')
    op.drop_index('idx_llm_custom_services_enabled', table_name='llm_custom_services')
    op.drop_table('llm_custom_services')
    op.drop_index('idx_llm_virtual_keys_created_at', table_name='llm_virtual_keys')
    op.drop_index('idx_llm_virtual_keys_user', table_name='llm_virtual_keys')
    op.drop_index('idx_llm_virtual_keys_user_status', table_name='llm_virtual_keys')
    op.drop_table('llm_virtual_keys')
    op.drop_index('idx_llm_usage_events_created_at', table_name='llm_usage_events')
    op.drop_index('idx_llm_usage_events_model', table_name='llm_usage_events')
    op.drop_index('idx_llm_usage_events_user', table_name='llm_usage_events')
    op.drop_table('llm_usage_events')
    op.add_column('assets', sa.Column('source', sa.String(length=50), server_default=sa.text("'manual'"), nullable=False))
    op.add_column('assets', sa.Column('script_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assets', 'scripts', ['script_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_episodes_episode_doc_node_id', table_name='episodes')
    op.drop_index('idx_image_prompts_storyboard', table_name='image_prompts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_image_prompts_storyboard', 'image_prompts', ['storyboard_id'], unique=False)
    op.create_index('idx_episodes_episode_doc_node_id', 'episodes', ['episode_doc_node_id'], unique=False)
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'script_id')
    op.drop_column('assets', 'source')
    op.create_table('llm_usage_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=18, scale=10), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='llm_usage_events_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='llm_usage_events_pkey')
    )
    op.create_index('idx_llm_usage_events_user', 'llm_usage_events', ['user_id'], unique=False)
    op.create_index('idx_llm_usage_events_model', 'llm_usage_events', ['model'], unique=False)
    op.create_index('idx_llm_usage_events_created_at', 'llm_usage_events', ['created_at'], unique=False)
    op.create_table('llm_virtual_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=32), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.Column('litellm_key_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('key_prefix', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('encrypted_token', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'revoked'::character varying, 'expired'::character varying]::text[])", name='ck_llm_virtual_keys_status'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='llm_virtual_keys_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='llm_virtual_keys_pkey'),
    sa.UniqueConstraint('key_hash', name='uq_llm_virtual_keys_key_hash')
    )
    op.create_index('idx_llm_virtual_keys_user_status', 'llm_virtual_keys', ['user_id', 'status'], unique=False)
    op.create_index('idx_llm_virtual_keys_user', 'llm_virtual_keys', ['user_id'], unique=False)
    op.create_index('idx_llm_virtual_keys_created_at', 'llm_virtual_keys', ['created_at'], unique=False)
    op.create_table('llm_custom_services',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=32), server_default=sa.text("'openai_compatible'::character varying"), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('supported_models', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_models', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('encrypted_api_key', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("kind::text = 'openai_compatible'::text", name='ck_llm_custom_services_kind'),
    sa.PrimaryKeyConstraint('id', name='llm_custom_services_pkey'),
    sa.UniqueConstraint('name', name='uq_llm_custom_services_name')
    )
    op.create_index('idx_llm_custom_services_enabled', 'llm_custom_services', ['enabled'], unique=False)
    op.create_index('idx_llm_custom_services_created_at', 'llm_custom_services', ['created_at'], unique=False)
    op.create_table('llm_usage_daily',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('request_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=18, scale=10), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='llm_usage_daily_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='llm_usage_daily_pkey'),
    sa.UniqueConstraint('user_id', 'date', 'model', name='uq_llm_usage_daily_user_date_model')
    )
    op.create_index('idx_llm_usage_daily_user_date', 'llm_usage_daily', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###
